# Generated by Django 4.0.4 on 2022-04-26 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('organization', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Сотрудники',
                'db_table': 'employees',
                'unique_together': {('last_name', 'first_name', 'middle_name')},
            },
        ),
        migrations.CreateModel(
            name='Equipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Тип оборудования',
                'db_table': 'equipments',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Наименование объекта',
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='RepairPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Место ремонта',
                'db_table': 'repair_place',
            },
        ),
        migrations.CreateModel(
            name='Systems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Типы систем',
                'db_table': 'systems',
            },
        ),
        migrations.CreateModel(
            name='Spares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(blank=True, max_length=100, null=True)),
                ('issued_dt', models.DateField(blank=True, null=True)),
                ('serial_spare', models.CharField(blank=True, max_length=100, null=True)),
                ('returned_dt', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, max_length=500, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='spares_equipment_name', to='logistics.equipments', verbose_name='Идентификатор оборудования')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='spares_location_name', to='logistics.location', verbose_name='Идентификатор объекта')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='spares_system_name', to='logistics.systems', verbose_name='Идентификатор системы')),
            ],
            options={
                'verbose_name': 'Запасные части и принадлежности',
                'db_table': 'spares',
            },
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(blank=True, max_length=100, null=True)),
                ('accepted_dt', models.DateField(blank=True, null=True)),
                ('shipped_repair_dt', models.DateField(blank=True, null=True)),
                ('accepted_repair_dt', models.DateField(blank=True, null=True)),
                ('serial2', models.CharField(blank=True, max_length=100, null=True)),
                ('issued_dt', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, max_length=500, null=True)),
                ('issued_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='issued_location_name', to='logistics.location', verbose_name='Идентификатор объекта')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='equipment_name', to='logistics.equipments', verbose_name='Идентификатор оборудования')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='location_name', to='logistics.location', verbose_name='Идентификатор объекта')),
                ('repair_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='repair_name', to='logistics.repairplace', verbose_name='Идентификатор места ремонта')),
                ('responsible_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='employee_name', to='logistics.employees', verbose_name='Идентификатор сотрудника')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='system_name', to='logistics.systems', verbose_name='Идентификатор системы')),
            ],
            options={
                'verbose_name': 'Основная таблица',
                'db_table': 'main',
            },
        ),
        migrations.AddField(
            model_name='equipments',
            name='equipment_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='logistics.systems', verbose_name='Идентификатор системы'),
        ),
    ]
